version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store-app
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - products-store-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - products-store-rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    image: dannelysbeth/products-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE_NAME: store-app-queue
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: store-app
    depends_on: 
      - mysql
      - rabbitmq

  notifications-api:
    image: dannelysbeth/notifications-api:1.0.0
    ports:
      - "5001:5001"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE_NAME: store-app-queue
    depends_on: 
      rabbitmq:
        condition: service_healthy

  frontend:
    image: dannelysbeth/store-frontend:1.0.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes:
  products-store-mysql:
  products-store-rabbitmq:
